### ISSUE TITLE
[lxd container] ROS_IP env

### ISSUE THREAD

**Issue by fgonzalezr1998** [gentlebots/gb_robots#2]
Now, in the .bashrc file of the container, there is the next line: ``export ROS_IP=192.168.1.241``. However, if a user had to configure the lxd container with a different IP (for example, 192.168.0.241) because his subnet is different, this user will have to change this environment variable. There is one way to automatize this task so that the user have not to change anything. The solution is to change this line in .bashrc by:
```
export ROS_IP=`hostname -I | awk '{print $1}'`
```
I suggest to make this change and upload the new LXD container image

**Comment by jginesclavero** [comment]
Solved in the last container release. Thank you!
